// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	addItem: (name: string, quantity: number) => typedError<null, string>(__TAURI_INVOKE("add_item", { name, quantity })),
	getItems: () => typedError<ShoppingItem[], string>(__TAURI_INVOKE("get_items")),
};

/* Types */
export type ShoppingItem = {
	id: number,
	name: string,
	quantity: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

